apiVersion: v1
kind: Pod
metadata:
  name: selenium-hub
  labels:
    name: hub

spec:
   containers:
      - name: selenium-hub
        image: selenium/hub:3.141.59-20210311
        command: [ "sleep" ]
        args: [ "infinity" ]
        ports:
          - containerPort: 4444
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 60
          timeoutSeconds: 5
        